version: '2'
services:
  mongo1:
    image: mongo:4.4-withkey
    container_name: mongo1
    # command: --bind_ip_all --replSet dbrs --keyFile /keys/keyfile
    entrypoint: mongod --bind_ip_all --replSet dbrs --keyFile /keys/keyfile
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=dba
    #   - MONGO_INITDB_ROOT_PASSWORD=s3cr3tpass
    networks:
      - mongors-network
    ports:
      - 27017:27017
    links:
      - mongo2
      - mongo3
    volumes:
      - ./data/mongo1:/data/db
      - ./scripts:/scripts
      # - ./keyfile:/keys/keyfile
    restart: always
  mongo2:
    image: mongo:4.4-withkey
    container_name: mongo2
    # command: --bind_ip_all --replSet dbrs --keyFile /keys/keyfile
    entrypoint: ["mongod", "--bind_ip_all", "--replSet", "dbrs", "--keyFile", "/keys/keyfile"]
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=dba
    #   - MONGO_INITDB_ROOT_PASSWORD=s3cr3tpass
    networks:
      - mongors-network
    ports:
      - 27018:27017
    volumes:
      - ./data/mongo2:/data/db
      # - ./keyfile:/keys/keyfile
    restart: always
  mongo3:
    image: mongo:4.4-withkey
    container_name: mongo3
    # command: --bind_ip_all --replSet dbrs --keyFile /keys/keyfile
    entrypoint: ["mongod", "--bind_ip_all", "--replSet", "dbrs", "--keyFile", "/keys/keyfile"]
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=dba
    #   - MONGO_INITDB_ROOT_PASSWORD=s3cr3tpass
    networks:
      - mongors-network
    ports:
      - 27019:27017
    volumes:
      - ./data/mongo3:/data/db
      # - ./keyfile:/keys/keyfile
    restart: always

networks:
  mongors-network:
    driver: bridge